Dub Improvements
consumet/consumet.ts pull request #104
Opened 2022-11-09 21:17 UTC by ErrorErrorError

**What kind of change does this PR introduce?**
This pr fixes some issues where gogoanime was not returning the correct dub episodes. This also fixes issues where some providers might have bad search functionality when retrieving anime information. This will allow more accurate results when fetching for episodes.

**Did you add tests for your changes?**
Nope.

**If relevant, did you update the documentation?**
N/A

**Summary**
I want to be able to watch the correct episode and if I change providers, to make sure it returns the correct anime information.

**Other information**
This will require to run "npm run version" since I haven't done it yet.

2022-11-09 22:21 UTC, aidanjuma approved these changes
Looks good to me!

2022-11-09 22:23 UTC, riimuru commented on src/providers/meta/anilist.ts
> +          let secondRating = compareTwoStrings(targetTitle, b.title.toLowerCase())
Better to use `const` instead of `let` here. Same for the 2 variables above

2022-11-09 22:23 UTC, riimuru commented on src/providers/meta/anilist.ts
> +      let secondRating = compareTwoStrings(targetTitle, secondTitle.toLowerCase());
Use `const` instead of `let`

2022-11-09 22:24 UTC, aidanjuma commented on src/providers/meta/anilist.ts
> +      var secondTitle: string
Ahhh - well spotted. I'll change now. Thanks!!

2022-11-09 22:32 UTC, riimuru commented on src/providers/meta/anilist.ts
> +          if (s.page.toLowerCase() === this.provider.name.toLowerCase()) {
Yes

2022-11-09 22:44 UTC, riimuru requested changes

2022-11-09 22:44 UTC, riimuru commented on src/providers/meta/anilist.ts
> +      }
Unnecessary if statement scope brackets here too

2022-11-09 22:45 UTC, aidanjuma commented on src/providers/meta/anilist.ts
> +      }
Damn how do you spot these xD - will fix :D

2022-11-09 22:46 UTC, riimuru requested changes

2022-11-09 22:46 UTC, riimuru commented on src/providers/meta/anilist.ts
> +      if (typeof(b.title) == 'string') {
Unnecessary parentheses on typeof

2022-11-09 22:46 UTC, riimuru commented on src/providers/meta/anilist.ts
> +      if (typeof(a.title) == 'string') {
Unnecessary parentheses on `typrof`

2022-11-09 22:57 UTC, riimuru approved these changes
LGTM 👍

2022-11-09 22:58 UTC, merged

2022-11-10 02:11 UTC, riimuru commented on src/providers/meta/anilist.ts
> +      }
😄