feat(viewAsian): add viewAsian provider
consumet/consumet.ts pull request #110
Opened 2022-11-17 11:31 UTC by TDanks2000

**What kind of change does this PR introduce?**

added viewAsian as a provider

added asianLoad from branch dramacool as a extractor

2022-11-17 13:59 UTC, riimuru requested changes

2022-11-17 17:15 UTC, aidanjuma commented on src/providers/movies/viewAsian.ts
> +})();
Done 👍

2022-11-18 03:56 UTC, riimuru approved these changes
LGTM 👍

2022-11-18 18:20 UTC, riimuru requested changes

2022-11-18 18:20 UTC, riimuru commented on src/providers/movies/viewAsian.ts
> +      mediaInfo.release = $('.mvic-info p:contains(Release)').text().replace('Release: ', '').trim();
```suggestion
      mediaInfo.releaseDate = $('.mvic-info p:contains(Release)').text().replace('Release: ', '').trim();
```

2022-11-18 18:20 UTC, riimuru commented on docs/providers/viewAsian.md
> +    release: '2021',
```suggestion
    releaseDate: '2021',
```

2022-11-18 18:21 UTC, riimuru approved these changes

2022-11-18 18:21 UTC, merged