fix: `ComicK` provider
consumet/consumet.ts pull request #350
Opened 2023-06-29 05:46 UTC by hngngn

*What kind of change does this PR introduce?*

- bugfix

*Did you add tests for your changes?*

- No

*If relevant, did you update the documentation?*

- No

*Summary*

- Fix deprecated api used in `fetchAllChapters` and `getComicId`.
- Using fetch because axios always throw 403.
- typo in `ChapterData`

*Other information*

Not a native speaker, excuse my grammar

2023-06-29 11:58 UTC, riimuru requested changes

2023-06-29 11:58 UTC, riimuru commented on src/providers/manga/comick.ts
> +      const req = await fetch(`${this.apiUrl}/comic/${mangaId}`);
Can you use axios instead of fetch

2023-06-30 10:57 UTC, hngngn commented on src/providers/manga/comick.ts
> +      const req = await fetch(`${this.apiUrl}/comic/${mangaId}`);
yes, i use fetch because axios can't get the data and throw `403` all the time, but fixed by adding `Use-Agent`.

2023-07-05 14:51 UTC, riimuru approved these changes

2023-07-05 14:52 UTC, merged