new endpoint added in mangadex like fetchrandom,fetchRecentlyAdded,fe…
consumet/consumet.ts pull request #481
Opened 2024-03-01 01:57 UTC by kodify-js

**What kind of change does this PR introduce?**
=>refactoring

**Did you add tests for your changes?**
=>No
**If relevant, did you update the documentation?**
=>no
**Summary**
This change resolves #439 by adding fetchRecentlyAdded  fetchLatestUpdates fetchpopular fetchrandom in Mangadex endpoint

**Other information**

2024-03-01 18:15 UTC, riimuru reviewed
You would mind adding these new methods to docs?

2024-03-03 18:33 UTC, riimuru requested changes
Thank you for adding the docs!

2024-03-03 18:33 UTC, riimuru commented on src/providers/manga/mangadex.ts
> +  fetchrandom = async (
Can you change the function name to follow the camel case

2024-03-03 18:33 UTC, riimuru commented on src/providers/manga/mangadex.ts
> +  fetchpopular = async (
Change to camel case here too

2024-03-03 20:51 UTC, kodify-js commented on src/providers/manga/mangadex.ts
> +  fetchrandom = async (
ok

2024-03-03 20:51 UTC, kodify-js commented on src/providers/manga/mangadex.ts
> +  fetchpopular = async (
ok

2024-03-03 22:25 UTC, riimuru approved these changes

2024-03-03 22:26 UTC, merged