Fix(zoro): update the extractor in fetchEpisodeSources and update zoro domain.
consumet/consumet.ts pull request #482
Opened 2024-03-02 05:07 UTC by carlosesteven

- Update the scraper of the links (streaming and subtitles) of the anime extractor "zoro".
- Update domain from: https://hianime.to to https://hianime.to

URL: /anime/zoro/watch?episodeId=...

Change class: [rapidcloud.ts](https://github.com/carlosesteven/consumet.ts/blob/master/src/extractors/rapidcloud.ts) to: [megacloud.ts](https://github.com/carlosesteven/consumet.ts/blob/master/src/extractors/megacloud.ts)

Reason: rapidcloud.ts class used static keys from a [repository](https://github.com/consumet/consumet.ts/blob/master/src/extractors/rapidcloud.ts#L38) that no longer work. I replaced it with a class that extracts the decryption keys from the same code.

Use as a base this [extractor code](https://github.com/ghoshRitesh12/aniwatch-api/blob/main/src/extractors/megacloud.ts) and adapt it to the consumet.ts

**Did you add tests for your changes?**

No, tests already exist.

**Summary**

**Other information**

2024-03-03 18:29 UTC, riimuru requested changes

2024-03-03 18:29 UTC, riimuru commented on src/extractors/megacloud.ts
> +class MegaCloud {
Can you extend `VideoExtractor` here so then you can override the extract function and use `this.client.get` instead of `axios.get`

2024-03-03 18:40 UTC, riimuru requested changes

2024-03-03 18:40 UTC, riimuru commented on src/extractors/megacloud.ts
> +type intro_outro = {
This type isn't needed, use `Intro` imported from models instead.

2024-03-03 18:40 UTC, riimuru commented on src/extractors/megacloud.ts
> +      text = data;
change to `const test = data;`

2024-03-03 23:29 UTC, carlosesteven commented on src/extractors/megacloud.ts
> +class MegaCloud {
Check the new commit.

2024-03-03 23:29 UTC, carlosesteven commented on src/extractors/megacloud.ts
> +type intro_outro = {
Check the new commit.

2024-03-03 23:29 UTC, carlosesteven commented on src/extractors/megacloud.ts
> +      text = data;
Check the new commit.

2024-03-04 20:43 UTC, riimuru approved these changes

2024-03-04 20:43 UTC, merged