feat: meta/anilist fetchStaffById
consumet/consumet.ts pull request #567
Opened 2024-07-28 18:02 UTC by irfanshadikrishad

**What kind of change does this PR introduce?**

Implemented fetchStaffById in meta/anilist

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Summary**

**Other information**

2024-08-01 03:25 UTC, riimuru requested changes
Thank you for your pr! Everything else looks great

2024-08-01 03:25 UTC, riimuru commented on src/models/types.ts
> +export interface IStaffInfo {
can you rename this to `IStaff`

2024-08-01 04:40 UTC, irfanshadikrishad commented on src/models/types.ts
> +export interface IStaffInfo {
Done brother.

2024-08-03 05:51 UTC, riimuru approved these changes

2024-08-03 05:51 UTC, riimuru commented on src/models/types.ts
> +export interface IStaffInfo {
Thank youu!

2024-08-03 05:52 UTC, merged