feat(dramacool): Add recent-shows and recent-movies routes to DramaCool, trailer field to IMovieInfo, refactor(goku, moviehdwatch): Implement movie fetching by country and genre. Standardize outputs (e.g., remove `.replace('SS ', '')` from Goku).
consumet/consumet.ts pull request #574
Opened 2024-08-11 11:56 UTC by 2004durgesh

**What kind of change does this PR introduce?**
Added `recent-shows` and `recent-movies` routes to Dramacool, introduced a trailer field to `IMovieInfo`, and implemented movie fetching by country and genre. Additionally, standardized outputs from movie providers (e.g., removed `.replace('SS ', '')` from Goku).

**Did you add tests for your changes?**
Yes, I did

**If relevant, did you update the documentation?**
Yes, I did

**Summary**
As FlixHQ provides season and episode information, I wanted those changes applied to Goku and MovieHDWatch as well. Additionally, added recent-movies and recent-shows methods to Dramacool, since other movie providers also have these features.

**Other information**
No

2024-08-12 16:35 UTC, riimuru requested changes
Overall it looks great! 👍

2024-08-12 16:35 UTC, riimuru commented on src/providers/movies/flixhq.ts
> +          const latestEpisode = $(el).find('div.film-detail > div.fd-infor > span:nth-child(3)').text() ?? null
can you fix the indentation here? Thank youu

2024-08-12 16:44 UTC, 2004durgesh commented
done fixing indentation 👍

2024-08-14 02:12 UTC, riimuru approved these changes

2024-08-14 02:14 UTC, merged