feat(zoro): new methods + fix(anilist): type issue
consumet/consumet.ts pull request #584
Opened 2024-09-21 04:36 UTC by shubham7101

**What kind of change does this PR introduce?**

fix anilist type issue 
feat zoro new methods fetchSubbedAnime, fetchDubbedAnime, fetchMovie, fetchTV, fetchOVA, fetchONA, fetchSpecial, fetchGenres, genreSearch

**Did you add tests for your changes?**

Yes

2024-09-22 03:30 UTC, riimuru requested changes

2024-09-22 03:30 UTC, riimuru commented on src/providers/anime/zoro.ts
> +import { futimes } from 'fs';
remove unnecessary import

2024-09-22 03:30 UTC, riimuru commented
It looks great overall!

2024-09-24 11:18 UTC, shubham7101 commented on src/providers/anime/zoro.ts
> +import { futimes } from 'fs';
Fixed it.

2024-09-24 21:27 UTC, riimuru approved these changes

2024-09-24 21:28 UTC, merged