feat(multimovies): add new movie provider for Indian languages support in movies/anime
consumet/consumet.ts pull request #633
Opened 2024-12-22 15:21 UTC by 2004durgesh

**What kind of change does this PR introduce?**

- Added a new movie provider, `MultiMovies`, to enhance support for Indian regional languages.  
- Implemented headers in `dramacool` for improved proxying of sources.  
- Introduced a `characters` property/field (array) in `info` in `tmdb`. 

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
Yes
**Summary**

This pull request adds `MultiMovies` as a new movie provider to support Indian regional languages and updates `dramacool` with headers for better source proxying. It also introduces a `characters` array in the TMDB schema, enriching metadata and improving content management. These changes enhance platform accessibility and user experience.

**Other information**
None

2025-01-27 14:20 UTC, riimuru commented on src/providers/movies/dramacool.ts
> +})();
Could you comment this back

2025-01-27 14:21 UTC, riimuru requested changes
Thank you!

2025-01-27 14:21 UTC, riimuru commented on src/providers/movies/multimovies.ts
> +})();
Commend this one too

2025-01-27 15:41 UTC, 2004durgesh commented
Done, let me know if something else has to be done

2025-01-30 15:48 UTC, riimuru approved these changes

2025-01-30 15:49 UTC, merged

2025-01-31 06:03 UTC, YoJames2019 commented on dist/providers/movies/multimovies.js
> +    const movieInfo = await movie.fetchEpisodeSources('episodes/jujutsu-kaisen-1x2/');
why is this still here

2025-01-31 06:30 UTC, YoJames2019 commented
I think you forgot to compile before merging this....

2025-02-01 10:54 UTC, 2004durgesh commented
Sorry about that! I'll make a new PR to fix those issues. Is my recent PR causing all of Consumet to stop working?